image: php:7.0

cache:
  paths:
    - vendor/

before_script:
  - apt-get update -yqq
  - apt-get install git wget unzip -yqq
  - mkdir -p ~/.ssh && ssh-keyscan -H 'gitlab.nordkirche.de' >> ~/.ssh/known_hosts
  - wget https://composer.github.io/installer.sig -O - -q | tr -d '\n' > installer.sig
  - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
  - php -r "if (hash_file('SHA384', 'composer-setup.php') === file_get_contents('installer.sig')) { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
  - php composer-setup.php
  - php -r "unlink('composer-setup.php'); unlink('installer.sig');"
  - php composer.phar install

test:
  stage: test
  script:
    - ./vendor/bin/phpunit --configuration phpunit.xml
    - ./vendor/bin/phpunit --configuration phpunit.integration.xml
    # - ./vendor/bin/phpunit --configuration phpunit.e2e.xml